version: '3.8'

services:
  backend:
    container_name: ecommerce_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    networks:
      - npm_default

  frontend:
    container_name: ecommerce_frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3005:80"
    networks:
      - npm_default

networks:
  npm_default:
    external: true
